services:
  namesrv:
    image: apache/rocketmq:5.3.2
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    deploy:
      resources:
        limits:
          memory: 600m
    command: sh mqnamesrv
    environment:
      - JAVA_OPTS=-Xmx384m -Xms384m -XX:+UseG1GC 
        - XX:MaxMetaspaceSize=128m
        -XX:+ExplicitGCInvokesConcurrent
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c 'cat < /dev/null > /dev/tcp/localhost/9876' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [qr_network]
  broker:
    image: apache/rocketmq:5.3.2
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    deploy:
      resources:
        limits:
          memory: 1200m
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx768m -Xms768m
        -XX:+UseG1GC
        -XX:G1HeapRegionSize=16m
        -XX:MaxGCPauseMillis=200
        -XX:InitiatingHeapOccupancyPercent=35
        -XX:G1ReservePercent=15
        -XX:MaxDirectMemorySize=256m
        -XX:MaxMetaspaceSize=128m
    depends_on:
      namesrv:
        condition: service_healthy
    volumes:
      - ../configs/rmq/broker.conf:/home/rocketmq/conf/broker.conf
      - ../data/rmq/store:/home/rocketmq/store
    command: sh mqbroker -n rmqnamesrv:9876 autoCreateTopicEnable=true autoCreateSubscriptionGroup=true
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c 'cat < /dev/null > /dev/tcp/localhost/10911' || exit 1"]
      interval: 8s
      timeout: 5s
      retries: 10
    networks: [qr_network]

  proxy:
    image: apache/rocketmq:5.3.2
    container_name: rmqproxy
    ports:
      - 8080:8080  # 控制台端口
      - 8081:8081  # gRPC端口
      - 8082:8082  # HTTP管理端口
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
      - JAVA_OPTS=-Xmx512m -Xms512m -XX:+UseG1GC -XX:MaxDirectMemorySize=192m -XX:MaxMetaspaceSize=128m
    command:
      - sh
      - mqproxy
      - --proxyMode=local
      - --namesrvAddr=rmqnamesrv:9876
      - --proxyConfigPath=/home/rocketmq/conf/proxy.conf
    depends_on:
      namesrv:
        condition: service_healthy
      broker:
        condition: service_healthy
    volumes:
      - ../configs/rmq/proxy.conf:/home/rocketmq/conf/proxy.conf
      - ../data/rmq/rmqproxy:/home/rocketmq/logs
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf --max-time 8 --retry 5 http://localhost:8082/health || exit 1" ]
      start_period: 60s  # 延长初始等待时间
      interval: 10s
      timeout: 8s
      retries: 10
    networks: [qr_network]

  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-dashboard
    ports:
      - 8089:8080  # 宿主机端口:容器端口（避免与现有proxy端口冲突）
    deploy:
      resources:
        limits:
          memory: 400m
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Xmx128m -Xms128m
    depends_on:
      namesrv:
        condition: service_healthy
      broker:
        condition: service_healthy
      proxy:
        condition: service_healthy
    networks: [qr_network]

networks:
  qr_network:
    external: true  # 声明使用外部网络