spring:
  application:
    name: auth-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos123456
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service
  flyway:
    enabled: true
    locations: classpath:db/migration   # 迁移脚本路径
    baseline-on-migrate: true           # 自动初始化空数据库
    user: root                          # 数据库账号（需要 DDL 权限）
    password: root                # 数据库密码
    url: jdbc:mysql://localhost:3306/auth_db?useSSL=false # JDBC 连接
  r2dbc:
    url: r2dbc:mysql://nacos:nacos123456@localhost:3306/auth_db?useSSL=false
    username: nacos
    password: nacos123456
  data:
    redis:
      host: redis
      port: 6379
      password: redis123456
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
jwt:
  secret-key: DwXLs5v0Kmzxsu0Fzk9mEaZ2jNuo59xurph3gaOduQipuyh/l58JSJGNppZrbeZsXEQEWNRQ2uhkwNZ+z9lF4A==
  access-token-expire: PT2H
  refresh-token-expire: P7D

server:
  port: 8082