server:
  port: 8082
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service
  cloud:
    nacos:
      discovery:
        service: auth-service
        server-addr: localhost:8848  # 替换为实际 Nacos 地址
        username: nacos  # Nacos 服务端用户名（默认是 nacos）
        password: nacos  # Nacos 服务端密码（默认是 nacos）
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: redis2025
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 4