services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf  # 挂载配置文件
    networks:
      - qr-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "--no-auth-warning", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # 仅保留 root 密码
      - TZ=Asia/Shanghai
      - MYSQL_DEFAULT_AUTHENTICATION_PLUGIN=mysql_native_password
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf  # 明确挂载配置文件
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - qr-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 30s
      timeout: 30s
      retries: 10
    command:
      - --log-error-verbosity=3
      - --default-time-zone=+8:00
  nacos:
    image: nacos/nacos-server:v2.5.1
    container_name: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN=ziRt0uB6W4bGYny2Vq5AuhnZktJ5ZUPL75Xi9Pgj1fU=
      - NACOS_AUTH_IDENTITY_KEY=username
      - NACOS_AUTH_IDENTITY_VALUE=nacos
      - NACOS_AUTH_TOKEN_EXPIRE_SECONDS=18000
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=${NACOS_DB_PASSWORD}
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - qr-network

  sentinel:
    image: bladex/sentinel-dashboard:1.8.6
    container_name: sentinel
    ports:
      - "8080:8858"
    environment:
      - AUTH_USERNAME=sentinel
      - AUTH_PASSWORD=${SENTINEL_AUTH_PASSWORD}
    networks:
      - qr-network

  rmqnamesrv:
    image: apache/rocketmq:5.1.4
    container_name: rmqnamesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv
    networks:
      - qr-network

  rmqbroker:
    image: apache/rocketmq:5.1.4
    container_name: rmqbroker
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
      - JAVA_OPT_EXT=-server -Xms512m -Xmx512m
    command: sh mqbroker -c /home/rocketmq/conf/broker.conf
    volumes:
      - ./broker.conf:/home/rocketmq/conf/broker.conf  # 挂载配置文件
    depends_on:
      - rmqnamesrv
    networks:
      - qr-network

  seata:
    image: seataio/seata-server:2.0.0
    container_name: seata
    ports:
      - "8091:8091"
    environment:
      - SEATA_IP=${SEATA_IP}  # 替换为你的本机 IP
      - STORE_MODE=db
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=seata
      - DB_PASSWORD=${SEATA_DB_PASSWORD}
      - SEATA_CONFIG_NACOS_USERNAME=nacos
      - SEATA_CONFIG_NACOS_PASSWORD=${SEATA_CONFIG_NACOS_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - qr-network

networks:
  qr-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: