services:
  mysql:
    container_name: mysql
    image: mysql:8.0.31  # 直接使用官方镜像
    environment:
      - MYSQL_INNODB_BUFFER_POOL_SIZE=128M  # 核心参数
      - MYSQL_PERFORMANCE_SCHEMA=OFF        # 关闭性能模式
    deploy:
      resources:
        limits:
          memory: 256m                     # 容器内存硬限制
          cpus: "0.5"
    env_file:
      - ./mysql.env
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro  # 时区配置
      # 初始化 SQL 文件挂载（添加只读权限）
      - ../configs/mysql/0-init.sql:/docker-entrypoint-initdb.d/0-init.sql:ro
      - ../configs/mysql/1-nacos-schema.sql:/docker-entrypoint-initdb.d/1-nacos-schema.sql:ro
      - ../configs/mysql/2-seata-schema.sql:/docker-entrypoint-initdb.d/2-seata-schema.sql:ro
      - ../configs/mysql/3-custom.sql:/docker-entrypoint-initdb.d/3-custom.sql:ro
      # 数据持久化
      - ../data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    command: [
      "mysqld",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    networks: [ qr_network ]

networks:
  qr_network:
    external: true  # 声明使用外部网络