server:
  port: 8081
jwt:
  secret: "your-256-bit-secret-key-here-must-be-at-least-32-chars"  # 替换为实际密钥
spring:
  cloud:
    # 网关配置
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
            - name: RequestRateLimiter
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
    # Nacos 服务发现
    nacos:
      discovery:
        service: gateway-service
        server-addr: localhost:8848  # 替换为实际 Nacos 地址
        username: nacos  # Nacos 服务端用户名（默认是 nacos）
        password: nacos  # Nacos 服务端密码（默认是 nacos）

    # Sentinel 流量控制
    sentinel:
      eager: true # 立即初始化
      transport:
        dashboard: localhost:8080  # 替换为实际 Sentinel 控制台地址
        port: 8719 # 本地端口
      filter:
        enabled: false # 禁用默认的Servlet Filter