audit:
  retention-days: 18    # 日志保留天数
  sensitive-fields: password,token  # 敏感字段列表
spring:
  application:
    name: user-service
  cloud:
    nacos:
      config:
        server-addr: localhost:8848  # 使用容器名而非 127.0.0.1
        username: nacos
        password: nacos123456
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos123456
        grpc:
          server-addr: nacos:9848
    seata:
      enabled: true
      application-id: user-service
      tx-service-group: default_tx_group
      service:
        vgroup-mapping:
          default_tx_group: default
      registry:
        type: nacos
        nacos:
          server-addr: localhost:8848
          namespace: public
          group: SEATA_GROUP
          username: nacos
          password: nacos123456
      config:
        type: nacos
        nacos:
          server-addr: localhost:8848
          namespace: public
          group: SEATA_GROUP
          username: nacos
          password: nacos123456
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service

  r2dbc:
    url: r2dbc:mysql://localhost:3306/user_db?useSSL=false
    username: nacos
    password: nacos123456
    pool:
      initial-size: 5
      max-size: 10

  data:
    redis:
      host: redis  # 使用容器名
      port: 6379
      password: redis123456
      lettuce:
        pool:
          max-active: 8
          max-idle: 8

  flyway:
    enabled: true
    locations: classpath:db/migration
    repair-on-migrate: true # 启动时自动修复校验和不匹配问题
    baseline-on-migrate: true # 如果存在基线迁移则忽略历史
    user: root
    password: root
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false

  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

jwt:
  secret-key: cg4dpZmWWQILnibVF8i40TKp/URCsT0hzDISsykTMP0=
  access-token-expire: 2h # 访问令牌有效期
  refresh-token-expire: 7d # 刷新令牌有效期
server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  metrics:
    tags:
      application: ${spring.application.name}
