spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service

  r2dbc:
    url: r2dbc:mysql://localhost:3306/user_db?useSSL=false
    username: root
    password: root123456

  data:
    redis:
      host: localhost
      port: 6379
      password: redis2025
      lettuce:
        pool:
          max-active: 8
          max-idle: 8

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: root
    password: root123456
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false

jwt:
  secret-key: ziRt0uB6W4bGYny2Vq5AuhnZktJ5ZUPL75Xi9Pgj1fU=

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics