version: "3.8"
services:
  sentinel:
    image: bladex/sentinel-dashboard:1.8.6
    container_name: sentinel
    ports:
      - "8858:8858"
      - "8719:8719"
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx512m
      - SERVER_PORT=8858
      - AUTH_USERNAME=sentinel
      - AUTH_PASSWORD=${SENTINEL_AUTH_PASSWORD}
    volumes:
      - ../data/sentinel/logs:/root/logs/csp
    networks: [qr_network]

networks:
  qr_network:
    external: true  # 声明使用外部网络